Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"
    config.vm.hostname = "jaflar.fjeclot.net"
    config.vm.provider "virtualbox" do |v|
      # v.gui = true
      v.name = "jaflar"
      v.memory = 2048
      v.cpus = 2
      v.customize ['modifyvm', :id, '--clipboard', 'bidirectional']     
    end
    
    config.vm.network "public_network"
    
    config.vm.network "forwarded_port", guest: 80, host: 18000 
    config.vm.network "forwarded_port", guest: 8080, host: 18000
    config.vm.network "forwarded_port", guest: 8888, host: 18000


   config.vm.synced_folder "../codi ", "/var/www/html"

    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      sudo apt-get install -y aptitude
      sudo apt-get upgrade -y 
      sudo apt-get install -y apache2 apache2-doc
      sudo apt-get install -y apache2-doc
      sudo apt-get install -y libapache2-mod-php
      sudo apt-get install -y php7.4
      sudo apt-get install -y mariadb-server
      sudo apt-get install -y madiadb-client
      sudo apt-get install -y net-tools
      sudo apt-get install -y aptitude
      sudo apt-get install -y php7.4-mysql
      sudo apt-get install -y composer
    SHELL
  
  end
